expr_name: 5s8r1c-01
is_restart: false
ns: 6
nr: 8
nc: 1

lb: 1.e-8
n_epoch: 5000
n_plot: 10
grad_max: 1.e2
maxiters: 50000

lr_max: 2.e-3
lr_min: 1.e-5
lr_decay: 0.5
lr_decay_step: 500
w_decay: 1.e-8