expr_name: 5s8r1c-11
is_restart: false
ns: 6
nr: 8
nc: 1

lb: 1.e-8
n_epoch: 2500
n_plot: 10
grad_max: 1.e2
maxiters: 50000

lr_max: 4.e-3
lr_min: 1.e-5
lr_decay: 0.5
lr_decay_step: 100
w_decay: 1.e-8